---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin-user-2
  labels:
    strimzi.io/cluster: kafka-broker-2
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - Create
          - Describe
          - Read
          - Write
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - Read
