---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: kafka-mirror
spec:
  version: 3.4.0
  replicas: 1
  # The cluster alias for Kafka Connect
  connectCluster: "uat-gcp-us-west1-leopard-confluent"
  clusters:
  ############### SOURCE CLUSTER (Active) ################
  - alias: "uat-gcp-us-west1-leopard-confluent-sso"
    bootstrapServers: pkc-lgk0v.us-west1.gcp.confluent.cloud:9092
    authentication: 
      type: plain
      username: QDDKG5MRZFQ5KG3D
      passwordSecret:
        secretName: uat-gcp-us-west1-leopard
        password: QDDKG5MRZFQ5KG3D.password
    config:
      # -1 means it will use the default replication factor configured in the broker
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1   
      # security
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
  ############### TARGET CLUSTER (Passive) ################        
  - alias: "uat-gcp-us-west1-leopard-confluent"
    bootstrapServers: pkc-lgk0v.us-west1.gcp.confluent.cloud:9092
    authentication:
      type: plain
      username: OOECKHKYW5R64RHQ
      passwordSecret:
        secretName: uat-gcp-us-west1-leopard
        password: OOECKHKYW5R64RHQ.password
    tls:
      trustedCertificates: []
    config:
      # The following KafkaConnect topics are created by default. You can change the default
      # replication factors (it is 3) and their names here.
      #
      # Kafka topic that stores connector and task status configurations
      # Replication factor for internal topic 'mirrormaker2-cluster-configs'
      config.storage.replication.factor: 3
      config.storage.topic: mirrormaker2-cluster-configs
      #
      # Kafka topic that stores connector offsets.
      # Replication factor for internal topic 'mirrormaker2-cluster-offsets'
      offset.storage.replication.factor: 3
      offset.storage.topic: mirrormaker2-cluster-offsets
      #
      # Kafka topic that stores connector and task status updates.
      # Replication factor for internal topic 'mirrormaker2-cluster-status'
      status.storage.replication.factor: 3
      status.storage.topic: mirrormaker2-cluster-status
      # security
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
  mirrors:
  #######################
  # Replication flows
  #######################
  - sourceCluster: "uat-gcp-us-west1-leopard-confluent-sso"
    targetCluster: "uat-gcp-us-west1-leopard-confluent"
    sourceConnector:
      tasksMax: 1
      config:
        # The replication factor for mirrored topics created at the target cluster
        replication.factor: 1
        # The replication factor for the MirrorSourceConnector 'offset-syncs' internal topic
        # that maps the offsets of the source and target clusters.
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
        # Defines the separator used for the renaming of remote topics (useful when mirroring ACTIVE / ACTIVE clusters)
        replication.policy.separator: "."
        # Override automatic renaming (use this policy for ACTIVE / PASSIVE use cases)
        # Instead of prepending the name with the name of the source cluster, the topic retains its original name
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
        # Refresh interval to check new topics created in source cluster
        refresh.topics.interval.seconds: 60
    heartbeatConnector:
      config:
        # Internal topic 'heartbeats' created at the target cluster
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        # Internal topic '<source-cluster-alias>.checkpoints.internal' created at the target cluster
        checkpoints.topic.replication.factor: 1
        # Override automatic renaming (use this policy for ACTIVE / PASSIVE use cases)
        # Instead of prepending the name with the name of the source cluster, the topic retains its original name
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"        
        # Offset synchronization periodically transfers the consumer offsets for the consumer groups
        # of a source cluster into the consumer offsets topic of a target cluster.
        sync.group.offsets.enabled: true
        # Interval period to sync data offsets from source cluster
        #sync.group.offsets.interval.seconds: 60
        #emit.checkpoints.interval.seconds: 60
        # Interval period to refresh consumer groups statuses (Default: 600)
        refresh.groups.interval.seconds: 60
    # topicsPattern: ".*"
    topicsPattern: "eventbus.public.job-management-service.common-job-state.v1"
    # groupsPattern: ".*"
    groupsPattern: "ian_miller_mm2_test"
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
  readinessProbe:
    initialDelaySeconds: 45
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 45
    timeoutSeconds: 5
